title: Divesh Gaba
logo: /assets/img/DP (1).png
description: Currently, I am working as a senior Tech Support Executive.
Working on Excel, MySQL and Cloud Computing related problems.
Use CRM to store and analyze customer data to find insights and understand customer behaviour.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
