title: Divesh Gaba
logo: /assets/img/DP (1).png
description: Working on MySQL, Excel and Cloud Computing related problems.
Using CRM to analyze the customer data to find insights and understand user behaviour.
Working in Teleperformanc for 2 years.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
